services:
  - type: web
    name: cira-iiot
    env: python
    region: oregon
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir CODE/APP app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
